### ISSUE TITLE
 train_multi_gpus.py error

### ISSUE THREAD

**Issue by zuoxiang95** [Kyubyong/tacotron#53]
when i run train_multi_gpus.py, i get this error:
Traceback (most recent call last):
  File "train_multi_gpus.py", line 137, in <module>
    main()
  File "train_multi_gpus.py", line 117, in main
    g = Graph(); print("Training Graph loaded")
  File "train_multi_gpus.py", line 58, in __init__
    is_training=is_training) # (N, T', hp.n_mels*hp.r)
  File "/data1/zuoxiang/tacotron/networks.py", line 85, in decode1
    dec = attention_decoder(dec, memory, num_units=hp.embed_size) # (N, T', E)
  File "/data1/zuoxiang/tacotron/modules.py", line 247, in attention_decoder
    probability_fn=tf.nn.softmax)
TypeError: __init__() got an unexpected keyword argument 'probability_fn'

**Comment by zuoxiang95** [comment]
i have change num_gpus = 4 in heperparams.py

**Comment by zuoxiang95** [comment]
because my tensorflow's version is not 1.2.0 .  after i update the tensorflow's version to 1.2.0, it can work well.
